# Generated by Django 2.0.2 on 2023-03-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='group',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='informacion_personal',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='InformacionPersonal',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
