# Generated by Django 2.0.2 on 2023-04-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID bodega')),
                ('nombre_bodega', models.CharField(max_length=100, verbose_name='Nombre de bodega')),
                ('tamaño', models.CharField(choices=[('S', 'Bodega Standar'), ('L', 'Bodega Large'), ('XL', 'Bodega Extra-Large')], max_length=4, verbose_name='Tamaño')),
                ('tipo', models.CharField(choices=[('SECA', 'Bodega Seca'), ('FRÍA', 'Bodega Fría')], max_length=4, verbose_name='ID bodega')),
                ('arrendada', models.BooleanField(default=False, verbose_name='Arrendada')),
                ('fecha_inicio_arriendo', models.DateField(blank=True, null=True, verbose_name='Inicio del ')),
                ('fecha_fin_arriendo', models.DateField(blank=True, null=True, verbose_name='ID bodega')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre_bodega'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Local')),
                ('nombre_local', models.CharField(blank=True, help_text='Ingrese nombre del local', max_length=100, null=True, verbose_name='Nombre Local')),
                ('telefono', models.CharField(help_text='+xxx xxxxxxxx', max_length=13, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('encargado', models.CharField(help_text='Ingrese nombre y apellido del encargado', max_length=100, verbose_name='Encargado')),
                ('num_bodegas', models.IntegerField(verbose_name='Numero de bodegas')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre_local'],
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Local', verbose_name='Local'),
        ),
    ]
